<center><h1>Machine Learning Model Pipeline</h1></center>

In [1]:
# Data Manipulation
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

# System Settings
import warnings
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
sys.path.append(os.path.abspath('../atmoseer'))
sys.path.append(os.path.abspath('../utils'))
warnings.filterwarnings("ignore")

# Custom Database Operations
from utils.postgres_processor import load_table

In [2]:
co2_df = load_table("CO2DataNOAA", "postgres", "Godragons6")
co2_df.head().style.format(precision=2).set_properties(**{'border': '1.5px solid blue'}).background_gradient(cmap='coolwarm')